[tool.poetry]
name = "skypro-project-1"
version = "0.1.0"
description = ""
authors = ["Андрей Стюхин <andreyst@olovyannaya.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
openpyxl = "^3.1.5"
requests = "^2.32.3"
pytest = "^8.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
